import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getQuote } from '../lib/getQuote'

export async function getStaticProps(context){
  const quote = await getQuote()
  
  return {
    props: { quote }
    }
  }


export default function Home({quote}) {

  


  return (
    <div className={styles.container}>
      <Head>
        <title>trpstr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {quote ? quote : "no quote here"}
        </h1>


        
      </main>

    </div>
  )
}
